### ISSUE TITLE
Change the way to retrieve comments.

### ISSUE THREAD

**Issue by g-plane** [JamesHenry/typescript-estree#32]
Currently, this parser uses the scanner of TypeScript to retrieve comments. And there is an issue:

For example, we have code like this (please ignore the syntax highlight from GitHub):
```typescript
let jsx = <div>//not a comment</div>
```
As we can see above, the text in the `div` tag is `JSXText`, however, the `typescript-estree` regards it as comment and adds it to the `comments` property. Note that this only affected on the `comments` property if the `comments` option is on, while the AST and the `tokens` property work fine.

**Comment by shmidt-i** [comment]
Thats kinda critical, because you can have `<div>http://notacomment.com</div>` which will be treated as a comment

**Comment by kaicataldo** [comment]
I've run into this as well. I'd love to look at this at some point, but need to get to the rest of my OSS backlog first! Does anyone who might be more familiar with TS's internals have an idea of how this could be achieved a different way?

**Comment by armano2** [comment]
@kaicataldo @shmidt-i @g-plane issue is due to https://github.com/JamesHenry/typescript-estree/blob/master/src/parser.ts#L134

what you want is 
```ts
jsx: extra.jsx ? ts.JsxEmit.ReactNative : undefined
```

you should be able to specify one of 3 values there: `"preserve", "react", "react-native"`, but this will not be aligned with eslint :(

i think we should provide additional field like `jsxType` where you can specify this

**Comment by armano2** [comment]
@JamesHenry this got fixed in https://github.com/JamesHenry/typescript-estree/pull/82
