### ISSUE TITLE
Question: why is source code is not written in typescript?

### ISSUE THREAD

**Issue by styfle** [JamesHenry/typescript-estree#5]
**What did you expect to happen?**
Excepted source code files to use .ts

**What actually happened?**
Source code files actually uses .js

Why is that?

**Comment by kaicataldo** [comment]
I'm not sure I understand what the issue is. Is it just that this a TypeScript parser that isn't written in TypeScript? I'm not the original author, so I can't give you a definitive answer, but if so, there are a lot of valid reasons to not write a Node.js package in TypeScript (extra complexity around and infrastructure for compiling/releasing being the one that comes to my mind).

**Comment by styfle** [comment]
There is already a dependency on typescript and it looks like babel is being used for compiling

https://github.com/JamesHenry/typescript-estree/blob/c3ea1d2745d4f6c73b3a6427738c181fd3184d87/package.json#L35

**Comment by JamesHenry** [comment]
The explanation is actually very simple, the project was extracted from one which existed for many years under eslint, and eslint does not author packages in TypeScript :)

@styfle the reason for babel there is not for compiling, it is detailed in the README: https://github.com/JamesHenry/typescript-estree#ast-alignment-tests
