### ISSUE TITLE
Investigate the possibility of setting `jsx: true` based on file extension

### ISSUE THREAD

**Issue by JamesHenry** [JamesHenry/typescript-estree#9]
Port of https://github.com/eslint/typescript-eslint-parser/issues/399

**Comment by kaicataldo** [comment]
Is this something we'd still like to do here? I don't think this makes as much sense here as it did in `typescript-eslint-parser`. It doesn't look like the filename is referenced in the options, and it doesn't seem quite right to add it in for the sake of this, since you can already specify with the `ecmaFeatures.jsx` option.

**Comment by kaicataldo** [comment]
For what it's worth, `typescript-eslint-parser` is adding this behavior: https://github.com/eslint/typescript-eslint-parser/pull/543. I think it probably makes sense for Prettier to do the same?

**Comment by kaicataldo** [comment]
@JamesHenry Thoughts on closing this now?
